# options for analysis running
run:
  timeout: 2m

# output configuration options
output:
  # sorts results by: filepath, line and column
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

# all available settings of specific linters
linters-settings:
  gosimple:
    # Select the Go version to target. The default is '1.13'.
    go: "1.22"

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.22"
    checks: ["all"]

  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.22"

  unused:
    # Select the Go version to target. The default is '1.13'.
    go: "1.22"
