# (mandatory) 
# Path to coverprofile file (output of `go test -coverprofile` command)
profile: cover.out

# (optional) 
# When specified reported file paths will not contain local prefix in the output
local-prefix: "github.com/cameronbrill/brill-wtf-go"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  file: 0
  package: 0
  total: 0
