#%RAML 1.0
---
title: RAML Representation of RESTful API
baseUri: http://api.go-chi-docgen-example.com/v1
mediaType: application/json
version: v1.0
/link:
  /{slug}:
    get:
      displayName: GET /link/{slug}
      description: "Handler Function: ameronbrill/brill-wtf-go/rest/controller.LinkServiceController.ShortURLToLink-fm\nComment: "
  get:
    displayName: GET /link/
    description: "Handler Function: ameronbrill/brill-wtf-go/rest/controller.LinkServiceController.ShortURLToLink-fm\nComment: "
  post:
    displayName: POST /link/
    description: "Handler Function: ameronbrill/brill-wtf-go/rest/controller.LinkServiceController.NewLink-fm\nComment: "
