name: "Golang code checks"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: format go files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: "."
          gofmt-flags: "-l -d"
  lint:
    name: lint go files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          args: --config ./.golangci.yaml
          version: latest
  build:
    name: build go binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build binary
        run: go build .
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
