
name: "Github Action"

on:
  push:
  pull_request:

jobs:
  actionlint:
    name: lint workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1